spring:
 profiles:
  active:
  -dev

---
spring:
 profiles: dev #开发环境
 appliction:
  name:microservicecloud-config-atguigu-dev

---

 spring:
  profiles: text #测试环境
  application:
   name: microservicecloud-config-atguigu-tex
  
  #情保存为UTF-8格式